In [ ]:
#To Perform Data Cleaning

In [1]:
#Theory
'''Example:
Imagine you're a librarian organizing books in a library. Data cleaning is like sorting through the books
to remove any duplicates, fix torn pages, and organize them neatly on the shelves.
his ensures that visitors can easily find the books they need without any confusion.
Question: What is data cleaning in the context of machine learning?
Answer: Data cleaning refers to the process of identifying and correcting errors,
inconsistencies, and inaccuracies in a dataset to improve its quality and
reliability for analysis and modeling.

Question: Why is data cleaning important in machine learning?
Answer: Data cleaning is crucial because machine learning
models are highly sensitive to the quality of input data.
Cleaning the data ensures that the model is trained on accurate and
 reliable information, leading to better performance and more accurate predictions.

Question: What are some common techniques used in data cleaning?
Answer: Some common techniques include handling missing values,
removing duplicates, correcting errors, standardizing data formats, and outlier detection and removal.

Question: How do you handle missing values in a dataset?
Answer: Missing values can be handled by either removing the rows or
columns containing missing values, imputing them with a specific value (e.g., mean, median, mode),
 or using advanced techniques such as predictive modeling to estimate missing values.

Question: What is outlier detection, and why is it important in data cleaning?
Answer: Outlier detection involves identifying data points that significantly deviate from
 the rest of the dataset. Outliers can distort statistical analyses and machine learning models, leading to inaccurate results.
  Detecting and removing outliers helps improve the quality and reliability of the dataset.

Question: How do you deal with categorical variables during data cleaning?
Answer: Categorical variables can be encoded into numerical values using techniques such as one-hot encoding or
label encoding. This allows machine learning algorithms to process and analyze categorical data effectively.

Question: Can you provide an example of data cleaning in a real-world machine learning project?
Answer: Sure, in a project involving predicting housing prices, data cleaning might involve removing duplicates,
handling missing values in features like square footage or number of bedrooms, and removing outliers in variables like price or area.
Additionally, categorical variables like type of property might be encoded for model compatibility.



'''

'Example'

In [ ]:
# 1.	 Write a program in Python to perform data cleaning operations on the dataset containing information about employees. Consider the following dataset
#data = {

#   'Name': ["John", "Alice", "Bob", "Emily", "Mike"],
 #   "Age": [25, 30, None, 35, 40],
 #   "Gender": ["Male", "Female", "Unknown", "Female", "Male"],
  #  "City": ["New York", "Los Angeles", "Chicago", "", "San Francisco"]
#}

#CODE
# Importing required library
import pandas as pd

# Sample data with missing values and inconsistencies
data = {
    'Name': ["John", "Alice", "Bob", "Emily", "Mike"],
    "Age": [25, 30, None, 35, 40],
    "Gender": ["Male", "Female", "Unknown", "Female", "Male"],
    "City": ["New York", "Los Angeles", "Chicago", "", "San Francisco"]
}

# Convert the dictionary into a pandas DataFrame
df = pd.DataFrame(data)

# Display the original data
print("Original Data:")
print(df)
print()

# Data Cleaning Steps

# 1. Handling missing values in "Age" column with the median age
median_age = df["Age"].median()
df["Age"].fillna(median_age, inplace=True)

# 2. Handling inconsistent values
# Replace "Unknown" gender with "Other"
df["Gender"].replace("Unknown", "Other", inplace=True)

# 3. Handling White Spaces
# Remove leading and trailing white spaces from "City" column
df["City"] = df["City"].str.strip()

# 4. Handling Empty Spaces
# Remove empty strings in "City" column with "Unknown"
df["City"].replace('', "Unknown", inplace=True)

# Display the cleaned data
print("Cleaned Data:")
print(df)

Original Data:
    Name   Age   Gender           City
0   John  25.0     Male       New York
1  Alice  30.0   Female    Los Angeles
2    Bob   NaN  Unknown        Chicago
3  Emily  35.0   Female
4   Mike  40.0     Male  San Francisco

Cleaned Data:
    Name   Age  Gender           City
0   John  25.0    Male       New York
1  Alice  30.0  Female    Los Angeles
2    Bob  32.5   Other        Chicago
3  Emily  35.0  Female        Unknown
4   Mike  40.0    Male  San Francisco

In [ ]:
#2.	Write a program in Python to perform data cleaning operations on a dataset containing information about employees. Consider the following dataset #Sample data with inconsistencies and error
#data = {
 #   "Employee_ID": [101, 102, 103, 104, 105],
 #   "First_Name": [" John", "Alice", "Bob", "Emily", "Mike"],
 #   "Last_Name": ["Doe", "Smith", "Johnson", "Williams", ''],
   # "Age": [25, 30, 35, "thirty-six", 40],
  #  "Department": ["HR", "IT", "Marketing", "Finance", "Admin"],
 # "Salary": [50000, 60000, "Unknown", 75000, 80000]
#}

#Code:
import pandas as pd

# Sample data with inconsistencies and errors
data = {
    "Employee_ID": [101, 102, 103, 104, 105],
    "First_Name": [" John", "Alice", "Bob", "Emily", "Mike"],
    "Last_Name": ["Doe", "Smith", "Johnson", "Williams", ''],
    "Age": [25, 30, 35, "thirty-six", 40],
    "Department": ["HR", "IT", "Marketing", "Finance", "Admin"],
    "Salary": [50000, 60000, "Unknown", 75000, 80000]
}

# Convert the dictionary into a pandas DataFrame
df = pd.DataFrame(data)

# Display the original data
print("Original Data:")
print(df)
print()

# Data Cleaning Steps

# 1. Handling Missing Values
# Convert non-numeric "Age" values to NaN
df["Age"] = pd.to_numeric(df["Age"], errors='coerce')
# Replace missing values in "Age" column with median age
median_age = df["Age"].median()
df["Age"].fillna(median_age, inplace=True)

# Replace "Unknown" salary with "NaN"
df["Salary"] = pd.to_numeric(df["Salary"], errors="coerce")
# Replace missing values in "Salary" column with median salary
median_salary = df["Salary"].median()
df["Salary"].fillna(median_salary, inplace=True)

# 2. Handling all inconsistent Values
# Convert all text in "Last_Name" to uppercase
df["Last_Name"] = df["Last_Name"].str.upper()

# 3. Validating Data
# Check if "Department" values are from a predicted set of categories
valid_departments = ["HR", "IT", "Marketing", "Finance", "Admin"]
df["Department"] = df["Department"].apply(lambda x: x if x in valid_departments else "Other")

# Display the cleaned data
print("Cleaned Data:")
print(df)

Original Data:
   Employee_ID First_Name Last_Name         Age Department   Salary
0          101       John       Doe          25         HR    50000
1          102      Alice     Smith          30         IT    60000
2          103        Bob   Johnson          35  Marketing  Unknown
3          104      Emily  Williams  thirty-six    Finance    75000
4          105       Mike                    40      Admin    80000

Cleaned Data:
   Employee_ID First_Name Last_Name   Age Department   Salary
0          101       John       DOE  25.0         HR  50000.0
1          102      Alice     SMITH  30.0         IT  60000.0
2          103        Bob   JOHNSON  35.0  Marketing  67500.0
3          104      Emily  WILLIAMS  32.5    Finance  75000.0
4          105       Mike            40.0      Admin  80000.0

In [ ]:
#3.	Write a program in Python to perform data cleaning operations on a dataset containing information about Students. Consider the following data set Sample data with inconsistencies and error
#data = {
#   "Student_Id": [1, 2, 3, 4, 5],
#   "First_Name": ["John", "Alice", "Bob", "Emily", "Mike"],
#   'Last_Name': ["Doe", "Smith", "Johnson", "Williams", ''],
#   "Math_Score": [85, 90, "A", 75, 80],
#   "Science_Score": [92, 88, 85, 90, 95],
#   "English_Score": [78, 80, 82, 85, "B"],
#   "History_Score": [88, 85, 90, "C", 92],
#    "Grade": ["A", "B", "C", "D", "E"]
#}
#Code:

import pandas as pd

# Sample data with inconsistencies and errors
data = {
    "Student_Id": [1, 2, 3, 4, 5],
    "First_Name": ["John", "Alice", "Bob", "Emily", "Mike"],
    'Last_Name': ["Doe", "Smith", "Johnson", "Williams", ''],
    "Math_Score": [85, 90, "A", 75, 80],
    "Science_Score": [92, 88, 85, 90, 95],
    "English_Score": [78, 80, 82, 85, "B"],
    "History_Score": [88, 85, 90, "C", 92],
    "Grade": ["A", "B", "C", "D", "E"]
}

# Convert the dictionary into a pandas DataFrame
df = pd.DataFrame(data)

# Display the original data
print("Original Data:")
print(df)
print()

# Data cleaning steps

# 1. Handling Missing Values
# Convert non-numeric scores to NaN
for col in ["Math_Score", "Science_Score", "English_Score", "History_Score"]:
    df[col] = pd.to_numeric(df[col], errors="coerce")

# Fill missing values with mean of each subject
for col in ["Math_Score", "Science_Score", "English_Score", "History_Score"]:
    mean_score = df[col].mean()
    df[col].fillna(mean_score, inplace=True)

# 2. Handling Inconsistent VALUES
# Convert text based grades to NaN
df["Grade"] = df["Grade"].apply(lambda x: x if x in ["A", "B", "C", "D", "E"] else None)

# 3. Validating Data
# Check if scores are within a valid range (0 to 100)
for col in ["Math_Score", "Science_Score", "English_Score", "History_Score"]:
    df[col] = df[col].apply(lambda x: x if (isinstance(x, int) and 0 <= x <= 100) else None)

# 4. Standardizing Data
# Convert all text in "Last_Name" to Uppercase
df["Last_Name"] = df["Last_Name"].str.upper()

# Display the cleaned data
print("Cleaned Data:")
print(df)

Original Data:
   Student_Id First_Name Last_Name Math_Score  Science_Score English_Score  \
0           1       John       Doe         85             92            78
1           2      Alice     Smith         90             88            80
2           3        Bob   Johnson          A             85            82
3           4      Emily  Williams         75             90            85
4           5       Mike                   80             95             B

  History_Score Grade
0            88     A
1            85     B
2            90     C
3             C     D
4            92     E

Cleaned Data:
   Student_Id First_Name Last_Name Math_Score  Science_Score English_Score  \
0           1       John       DOE       None             92          None
1           2      Alice     SMITH       None             88          None
2           3        Bob   JOHNSON       None             85          None
3           4      Emily  WILLIAMS       None             90          None
4           5       Mike                 None             95          None

  History_Score Grade
0          None     A
1          None     B
2          None     C
3          None     D
4          None     E

In [ ]:
#4)	Write a program in Python to perform data cleaning operations on a dataset containing information about the Customer. Consider the following data set
#data = {
#   "Customer_Id": [101, 102, 103, 104, 105],
#   "First_Name": [" John", "Alice", "Bob", "Emily", "Mike"],
#   "Last_Name": ["Doe", "Smith", "Johnson", "Williams", ''],
#   "Age": [25, 30, 35, "thirty-six", 40],
#   "Gender": ["M", "F", "Male", "Female", "Male"],
#   "Email": ["john.doe@example.com", "alice.smith@example.com", "bob.johnson@example.com", "emily.williams@example.com", "Mike@gmail.com"],
#   "Phone": ["123-456-7890", "555-555-5555", "999-999-9999", '', "111-111-1111"]
#}
#Code:
import pandas as pd

# Sample Customer data with inconsistencies and errors
data = {
    "Customer_Id": [101, 102, 103, 104, 105],
    "First_Name": [" John", "Alice", "Bob", "Emily", "Mike"],
    "Last_Name": ["Doe", "Smith", "Johnson", "Williams", ''],
    "Age": [25, 30, 35, "thirty-six", 40],
    "Gender": ["M", "F", "Male", "Female", "Male"],
    "Email": ["john.doe@example.com", "alice.smith@example.com", "bob.johnson@example.com", "emily.williams@example.com", "Mike@gmail.com"],
    "Phone": ["123-456-7890", "555-555-5555", "999-999-9999", '', "111-111-1111"]
}

# Convert the dictionary into a pandas DataFrame
df = pd.DataFrame(data)

# Display the original data
print("Original Customer Data:")
print(df)
print()

# Data cleaning steps

# 1. Handling Missing Values
# Convert non-numeric Age to NaN
df['Age'] = pd.to_numeric(df['Age'], errors='coerce')
# Replace missing values in Age column with median age
median_age = df["Age"].median()
df["Age"].fillna(median_age, inplace=True)

# Replace empty strings in "Last_Name" and "Phone" columns with NaN
df["Last_Name"].replace('', pd.NA, inplace=True)
df["Phone"].replace('', pd.NA, inplace=True)

# 2. Handling Inconsistent VALUES
# Standardize gender values to "Male", "Female" or "Other"
df["Gender"] = df["Gender"].str.lower().map({"m": "Male", "f": "Female"}).fillna("Other")

# 3. Validating Data
# Validate email address
def validate_email(email):
    if "@" in email:
        return email
    else:
        return pd.NA

df["Email"] = df["Email"].apply(validate_email)

# Display the cleaned data
print("Cleaned Customer Data:")
print(df)

Original Customer Data:
   Customer_Id First_Name Last_Name         Age  Gender  \
0          101       John       Doe          25       M
1          102      Alice     Smith          30       F
2          103        Bob   Johnson          35    Male
3          104      Emily  Williams  thirty-six  Female
4          105       Mike                    40    Male

                        Email         Phone
0        john.doe@example.com  123-456-7890
1     alice.smith@example.com  555-555-5555
2     bob.johnson@example.com  999-999-9999
3  emily.williams@example.com
4              Mike@gmail.com  111-111-1111

Cleaned Customer Data:
   Customer_Id First_Name Last_Name   Age  Gender                       Email  \
0          101       John       Doe  25.0    Male        john.doe@example.com
1          102      Alice     Smith  30.0  Female     alice.smith@example.com
2          103        Bob   Johnson  35.0   Other     bob.johnson@example.com
3          104      Emily  Williams  32.5   Other  emily.williams@example.com
4          105       Mike      <NA>  40.0   Other              Mike@gmail.com

          Phone
0  123-456-7890
1  555-555-5555
2  999-999-9999
3          <NA>
4  111-111-1111

In [ ]:
#5)	Write a program in Python to perform the data cleaning operation on a dataset containing information about Bank Customers. Consider the following dataset
#data = {
#"Customer_Id": [101, 102, 103, 104, 105],
#   "First_Name": ["John", "Alice", "Bob", "Emily", "Mike"],
#   "Last_Name": ["Doe", "Smith", "Johnson", "Williams", ''],
#   "Age": [25, 30, 35, "thirty-six", 40],
#   "Gender": ["M", "F", "Male", "Female", "M"],
#   "Account_Type": ["Savings", "Checking", "Unknown", "Savings", "Investment"],
#   "Balance": ["$5000", "$6000", "Unknown", "$7500", "10000"]
#}
#Code:
import pandas as pd

# Sample bank customer data with inconsistencies and errors
data = {
    "Customer_Id": [101, 102, 103, 104, 105],
    "First_Name": ["John", "Alice", "Bob", "Emily", "Mike"],
    "Last_Name": ["Doe", "Smith", "Johnson", "Williams", ''],
    "Age": [25, 30, 35, "thirty-six", 40],
    "Gender": ["M", "F", "Male", "Female", "M"],
    "Account_Type": ["Savings", "Checking", "Unknown", "Savings", "Investment"],
    "Balance": ["$5000", "$6000", "Unknown", "$7500", "10000"]
}

# Convert the dictionary into pandas DataFrame
df = pd.DataFrame(data)

# Display the original data
print("Original Bank Customer Data:")
print(df)
print()

# Data Cleaning Steps

# 1. Handling Missing Values
# Convert non-numeric Age to NaN
df['Age'] = pd.to_numeric(df['Age'], errors="coerce")
# Replace missing values in Age column with median age
median_age = df["Age"].median()
df["Age"].fillna(median_age, inplace=True)

# 2. Handling Inconsistent VALUES
# Standardize gender values to "Male", "Female" or "Other"
df["Gender"] = df["Gender"].str.lower().map({"m": "Male", "f": "Female"}).fillna("Other")

# Standardize account type values
valid_account_types = ["Savings", "Checking", "Investment"]
df["Account_Type"] = df["Account_Type"].apply(lambda x: x if x in valid_account_types else "Unknown")

# 3. Handling Invalid Balance Values
# Remove "$" sign and convert balance to numeric
df["Balance"] = pd.to_numeric(df["Balance"].replace({'\$': ''}, regex=True), errors="coerce")
# Replace missing balance values with 0
df["Balance"].fillna(0, inplace=True)

# Display the cleaned data
print("Cleaned Bank Customer Data:")
print(df)

Original Bank Customer Data:
   Customer_Id First_Name Last_Name         Age  Gender Account_Type  Balance
0          101       John       Doe          25       M      Savings    $5000
1          102      Alice     Smith          30       F     Checking    $6000
2          103        Bob   Johnson          35    Male      Unknown  Unknown
3          104      Emily  Williams  thirty-six  Female      Savings    $7500
4          105       Mike                    40       M   Investment    10000

Cleaned Bank Customer Data:
   Customer_Id First_Name Last_Name   Age  Gender Account_Type  Balance
0          101       John       Doe  25.0    Male      Savings   5000.0
1          102      Alice     Smith  30.0  Female     Checking   6000.0
2          103        Bob   Johnson  35.0   Other      Unknown      0.0
3          104      Emily  Williams  32.5   Other      Savings   7500.0
4          105       Mike            40.0    Male   Investment  10000.0